### ISSUE TITLE
No 'breathe' and 'wave' on MSI GX70 3BE

### ISSUE THREAD

**Issue by nikki-mccavee** [wearefractal/msi-keyboard#1]
`keyboard.mode('wave')` and `keyboard.mode('breathe')` don't produce the desired effect and, actually, turn off the keyboard lights

Hardware: MSI GX70 3BE (US version)
OS: Linux kernel 3.12.0 (x86_64)
NodeJS: v0.10.22

**Comment by Mrono** [comment]
I also have this issue on a GS70, breathe/wave works fine in windows and persists through warm reboot.  When I try to set said features via the library in linux it sets the keyboard to dark.  Blink works just fine.

**Comment by nikki-mccavee** [comment]
Good job @tobbebia It really does work with your changes.
