### ISSUE TITLE
CLI backlight

### ISSUE THREAD

**Issue by Kwaadpepper** [wearefractal/msi-keyboard#10]
Hi just to mention,
I wrote a cli interface to this keyboard API.
I you were intersted to use it.
https://github.com/Kwaadpepper/msi-keyboard-CLI

**Comment by stevelacy** [comment]
Send a PR to add the link to the readme file :smile:

**Comment by Kwaadpepper** [comment]
Just added https://github.com/wearefractal/msi-keyboard/pull/27
