### ISSUE TITLE
Python version not supported by gyp?

### ISSUE THREAD

**Issue by lama2p0** [wearefractal/msi-keyboard#16]
Can anyone help? This is the output I get after running 'npm install msi-keyboard'
Thanks..

>[laughingman@MSIManjaro895 ~]$ npm install msi-keyboard
>|
> node-hid@0.3.2 preinstall /home/laughingman/node_modules/msi-keyboard/node_modules/node-hid
> sh get-hidapi.sh
>
>Cloning into 'hidapi'...
>remote: Counting objects: 1965, done.
>remote: Total 1965 (delta 0), reused 0 (delta 0), pack-reused 1965
>Receiving objects: 100% (1965/1965), 2.79 MiB | 2.14 MiB/s, done.
>Resolving deltas: 100% (1082/1082), done.
>Checking connectivity... done.
>
> node-hid@0.3.2 install /home/laughingman/node_modules/msi-keyboard/node_modules/node-hid
> sh install.sh
>
>gyp ERR! configure error 
>gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
>gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
>gyp ERR! stack     at failPythonVersion (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
>gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
>gyp ERR! stack     at ChildProcess.exithandler (child_process.js:735:7)
>gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
>gyp ERR! stack     at maybeClose (child_process.js:1008:16)
>gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
>gyp ERR! System Linux 3.16.7.8-1-MANJARO
>gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" >"configure" "build" "install"
>gyp ERR! cwd /home/laughingman/node_modules/msi-keyboard/node_modules/node-hid
>gyp ERR! node -v v0.12.0
>gyp ERR! node-gyp -v v1.0.2
>gyp ERR! not ok 
>npm ERR! Linux 3.16.7.8-1-MANJARO
>npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "msi-keyboard"
>npm ERR! node v0.12.0
>npm ERR! npm  v2.7.1
>npm ERR! code ELIFECYCLE
>
>npm ERR! node-hid@0.3.2 install: `sh install.sh`
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the node-hid@0.3.2 install script 'sh install.sh'.
>npm ERR! This is most likely a problem with the node-hid package,
>npm ERR! not with npm itself.
>npm ERR! Tell the author that this fails on your system:
>npm ERR!     sh install.sh
>npm ERR! You can get their info via:
>npm ERR!     npm owner ls node-hid
>npm ERR! There is likely additional logging output above.
>
>npm ERR! Please include the following file with any support request:
>npm ERR!     /home/laughingman/npm-debug.log

**Comment by stevelacy** [comment]
This is not related to this project. Open on `nody-gyp`
