### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by schindlershadow** [wearefractal/msi-keyboard#18]
This may be an npm issue, but i'm not sure.

Getting the following error when installing:

$ npm install msi-keyboard
npm WARN package.json led-manager@ No description
npm WARN package.json led-manager@ No repository field.
npm WARN package.json led-manager@ No README data
|
> node-hid@0.3.2 preinstall /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid
> sh get-hidapi.sh

Cloning into 'hidapi'...
remote: Counting objects: 1965, done.
remote: Total 1965 (delta 0), reused 0 (delta 0), pack-reused 1965
Receiving objects: 100% (1965/1965), 2.79 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (1082/1082), done.
Checking connectivity... done.

> node-hid@0.3.2 install /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid
> sh install.sh

make: Entering directory '/home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c: In function ‘hid_read_timeout’:
../hidapi/libusb/hid.c:1078:6: warning: variable ‘bytes_read’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
  int bytes_read = -1;
      ^
  AR(target) Release/obj.target/hidapi.a
  COPY Release/hidapi.a
  CXX(target) Release/obj.target/HID/src/HID.o
../src/HID.cc: In member function ‘virtual v8::Handle<v8::Value> JSException::asV8Exception() const’:
../src/HID.cc:50:71: error: ‘New’ is not a member of ‘v8::String’
   virtual Handle<Value> asV8Exception() const { return ThrowException(String::New(message().c_str())); }
                                                                       ^
../src/HID.cc:50:101: error: ‘ThrowException’ was not declared in this scope
   virtual Handle<Value> asV8Exception() const { return ThrowException(String::New(message().c_str())); }
                                                                                                     ^
../src/HID.cc: At global scope:
../src/HID.cc:58:1: error: expected class-name before ‘{’ token
 {
 ^
../src/HID.cc:61:38: error: ‘Arguments’ does not name a type
   static Handle<Value> devices(const Arguments& args);
                                      ^
../src/HID.cc:76:34: error: ‘Arguments’ does not name a type
   static Handle<Value> New(const Arguments& args);
                                  ^
../src/HID.cc:77:35: error: ‘Arguments’ does not name a type
   static Handle<Value> read(const Arguments& args);
                                   ^
../src/HID.cc:78:36: error: ‘Arguments’ does not name a type
   static Handle<Value> write(const Arguments& args);
                                    ^
../src/HID.cc:79:36: error: ‘Arguments’ does not name a type
   static Handle<Value> close(const Arguments& args);
                                    ^
../src/HID.cc:80:45: error: ‘Arguments’ does not name a type
   static Handle<Value> setNonBlocking(const Arguments& args);
                                             ^
../src/HID.cc:81:47: error: ‘Arguments’ does not name a type
   static Handle<Value> getFeatureReport(const Arguments& args);
                                               ^
../src/HID.cc:83:48: error: ‘Arguments’ does not name a type
   static Handle<Value> sendFeatureReport(const Arguments& args);
                                                ^
../src/HID.cc:86:25: error: ‘uv_work_t’ has not been declared
   static void recvAsync(uv_work_t* req);
                         ^
../src/HID.cc:87:29: error: ‘uv_work_t’ has not been declared
   static void recvAsyncDone(uv_work_t* req);
                             ^
../src/HID.cc:177:16: error: variable or field ‘recvAsync’ declared void
 HID::recvAsync(uv_work_t* req)
                ^
../src/HID.cc:177:16: error: ‘uv_work_t’ was not declared in this scope
../src/HID.cc:177:27: error: ‘req’ was not declared in this scope
 HID::recvAsync(uv_work_t* req)
                           ^
In file included from ../src/HID.cc:30:0:
/home/schindler/.node-gyp/0.12.2/deps/v8/include/v8.h: In instantiation of ‘static void v8::NonCopyablePersistentTraits<T>::Uncompilable() [with O = v8::Object; T = v8::Object]’:
/home/schindler/.node-gyp/0.12.2/deps/v8/include/v8.h:592:17:   required from ‘static void v8::NonCopyablePersistentTraits<T>::Copy(const v8::Persistent<S, M>&, v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent*) [with S = v8::Object; M = v8::NonCopyablePersistentTraits<v8::Object>; T = v8::Object; v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent = v8::Persistent<v8::Object>]’
/home/schindler/.node-gyp/0.12.2/deps/v8/include/v8.h:5826:21:   required from ‘void v8::Persistent<T, M>::Copy(const v8::Persistent<S, M>&) [with S = v8::Object; M2 = v8::NonCopyablePersistentTraits<v8::Object>; T = v8::Object; M = v8::NonCopyablePersistentTraits<v8::Object>]’
/home/schindler/.node-gyp/0.12.2/deps/v8/include/v8.h:657:14:   required from ‘v8::Persistent<T, M>::Persistent(const v8::Persistent<T, M>&) [with T = v8::Object; M = v8::NonCopyablePersistentTraits<v8::Object>]’
../src/HID.cc:94:17:   required from here
/home/schindler/.node-gyp/0.12.2/deps/v8/include/v8.h:167:37: error: cannot convert ‘v8::Primitive*’ to ‘v8::Object* volatile’ in assignment
     *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                     ^
/home/schindler/.node-gyp/0.12.2/deps/v8/include/v8.h:596:5: note: in expansion of macro ‘TYPE_CHECK’
     TYPE_CHECK(O, Primitive);
     ^
/home/schindler/.node-gyp/0.12.2/deps/v8/include/v8.h: In instantiation of ‘static void v8::NonCopyablePersistentTraits<T>::Uncompilable() [with O = v8::Object; T = v8::Function]’:
/home/schindler/.node-gyp/0.12.2/deps/v8/include/v8.h:592:17:   required from ‘static void v8::NonCopyablePersistentTraits<T>::Copy(const v8::Persistent<S, M>&, v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent*) [with S = v8::Function; M = v8::NonCopyablePersistentTraits<v8::Function>; T = v8::Function; v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent = v8::Persistent<v8::Function>]’
/home/schindler/.node-gyp/0.12.2/deps/v8/include/v8.h:5826:21:   required from ‘void v8::Persistent<T, M>::Copy(const v8::Persistent<S, M>&) [with S = v8::Function; M2 = v8::NonCopyablePersistentTraits<v8::Function>; T = v8::Function; M = v8::NonCopyablePersistentTraits<v8::Function>]’
/home/schindler/.node-gyp/0.12.2/deps/v8/include/v8.h:657:14:   required from ‘v8::Persistent<T, M>::Persistent(const v8::Persistent<T, M>&) [with T = v8::Function; M = v8::NonCopyablePersistentTraits<v8::Function>]’
../src/HID.cc:94:17:   required from here
/home/schindler/.node-gyp/0.12.2/deps/v8/include/v8.h:167:37: error: cannot convert ‘v8::Primitive*’ to ‘v8::Object* volatile’ in assignment
     *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                     ^
/home/schindler/.node-gyp/0.12.2/deps/v8/include/v8.h:596:5: note: in expansion of macro ‘TYPE_CHECK’
     TYPE_CHECK(O, Primitive);
     ^
../src/HID.cc: In member function ‘virtual v8::Handle<v8::Value> JSException::asV8Exception() const’:
../src/HID.cc:50:104: warning: control reaches end of non-void function [-Wreturn-type]
   virtual Handle<Value> asV8Exception() const { return ThrowException(String::New(message().c_str())); }
                                                                                                        ^
HID.target.mk:94: recipe for target 'Release/obj.target/HID/src/HID.o' failed
make: *** [Release/obj.target/HID/src/HID.o] Error 1
make: Leaving directory '/home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.2-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "install"
gyp ERR! cwd /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.19.2-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "msi-keyboard"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! node-hid@0.3.2 install: `sh install.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.3.2 install script 'sh install.sh'.
npm ERR! This is most likely a problem with the node-hid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sh install.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-hid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/schindler/Downloads/msi-klm/npm-debug.log

Here is  /home/schindler/Downloads/msi-klm/npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'msi-keyboard' ]
2 info using npm@2.7.5
3 info using node@v0.12.2
4 warn package.json led-manager@ No description
5 warn package.json led-manager@ No repository field.
6 warn package.json led-manager@ No README data
7 silly cache add args [ 'msi-keyboard@*', null ]
8 verbose cache add spec msi-keyboard@*
9 silly cache add parsed spec { raw: 'msi-keyboard@*',
9 silly cache add   scope: null,
9 silly cache add   name: 'msi-keyboard',
9 silly cache add   rawSpec: '*',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 verbose addNamed msi-keyboard@*
11 silly addNamed semver.valid null
12 silly addNamed semver.validRange *
13 silly addNameRange { name: 'msi-keyboard', range: '*', hasData: false }
14 silly mapToRegistry name msi-keyboard
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry https://registry.npmjs.org/
17 silly mapToRegistry uri https://registry.npmjs.org/msi-keyboard
18 verbose addNameRange registry:https://registry.npmjs.org/msi-keyboard not in flight; fetching
19 verbose request uri https://registry.npmjs.org/msi-keyboard
20 verbose request no auth needed
21 info attempt registry request try #1 at 15:18:38
22 verbose request id 3a3db6a3a3c05224
23 verbose etag "5IIDKGSG98WCY8ASOXNKDULXH"
24 http request GET https://registry.npmjs.org/msi-keyboard
25 http 304 https://registry.npmjs.org/msi-keyboard
26 silly get cb [ 304,
26 silly get   { date: 'Sun, 05 Apr 2015 19:18:38 GMT',
26 silly get     server: 'Apache',
26 silly get     via: '1.1 varnish',
26 silly get     'last-modified': 'Sun, 05 Apr 2015 19:18:39 GMT',
26 silly get     'cache-control': 'max-age=60',
26 silly get     etag: '"5IIDKGSG98WCY8ASOXNKDULXH"',
26 silly get     age: '0',
26 silly get     'x-served-by': 'cache-jfk1022-JFK',
26 silly get     'x-cache': 'MISS',
26 silly get     'x-cache-hits': '0',
26 silly get     'x-timer': 'S1428261518.815458,VS0,VE350',
26 silly get     vary: 'Accept',
26 silly get     'content-length': '0',
26 silly get     'keep-alive': 'timeout=10, max=50',
26 silly get     connection: 'Keep-Alive' } ]
27 verbose etag https://registry.npmjs.org/msi-keyboard from cache
28 verbose get saving msi-keyboard to /home/schindler/.npm/registry.npmjs.org/msi-keyboard/.cache.json
29 silly addNameRange number 2 { name: 'msi-keyboard', range: '*', hasData: true }
30 silly addNameRange versions [ 'msi-keyboard', [ '0.0.1', '0.0.2' ] ]
31 verbose addNamed msi-keyboard@0.0.2
32 silly addNamed semver.valid 0.0.2
33 silly addNamed semver.validRange 0.0.2
34 silly cache afterAdd msi-keyboard@0.0.2
35 verbose afterAdd /home/schindler/.npm/msi-keyboard/0.0.2/package/package.json not in flight; writing
36 verbose afterAdd /home/schindler/.npm/msi-keyboard/0.0.2/package/package.json written
37 silly install resolved [ { name: 'msi-keyboard',
37 silly install resolved     description: 'MSI Keyboard LED Controller',
37 silly install resolved     version: '0.0.2',
37 silly install resolved     homepage: 'http://github.com/wearefractal/msi-keyboard',
37 silly install resolved     repository:
37 silly install resolved      { type: 'git',
37 silly install resolved        url: 'git://github.com/wearefractal/msi-keyboard.git' },
37 silly install resolved     author:
37 silly install resolved      { name: 'Fractal',
37 silly install resolved        email: 'contact@wearefractal.com',
37 silly install resolved        url: 'http://wearefractal.com/' },
37 silly install resolved     main: './index.js',
37 silly install resolved     dependencies: { 'node-hid': '*' },
37 silly install resolved     devDependencies: { mocha: '*', should: '*' },
37 silly install resolved     scripts: { test: 'mocha' },
37 silly install resolved     engines: { node: '>= 0.4.0' },
37 silly install resolved     licenses: [ [Object] ],
37 silly install resolved     readme: '[![Build Status](https://travis-ci.org/wearefractal/msi-keyboard.png?branch=master)](https://travis-ci.org/wearefractal/msi-keyboard)\n\n[![NPM version](https://badge.fury.io/js/msi-keyboard.png)](http://badge.fury.io/js/msi-keyboard)\n\n## Information\n\n<table>\n<tr> \n<td>Package</td><td>msi-keyboard</td>\n</tr>\n<tr>\n<td>Description</td>\n<td>MSI Keyboard LED Controller</td>\n</tr>\n<tr>\n<td>Hardware</td>\n<td>MSI GE, GT Steelseries Keyboard</td>\n</tr>\n<tr>\n<td>Node Version</td>\n<td>>= 0.4</td>\n</tr>\n</table>\n\n![keyboard](https://i.cloudup.com/V7zz0ZdHT8.png)\n\n## Usage\n\n```javascript\n// require the LED module\nvar keyboard = require(\'msi-keyboard\');\n\n// Set left region to high intensity, color red\nkeyboard.color(\'left\', {\n\tcolor: \'red\',\n\tintensity: \'high\'\n});\n\n// Set middle region to green default high intensity\nkeyboard.color(\'middle\', \'green\');\n\n\n// Set right region to blue with light intensity\nkeyboard.color(\'right\', {\n\tcolor: \'blue\',\n\tintensity: \'light\',\n});\n\n\n// Hardware modes\n// Setting .color() will Not affect the hardware defined colors for modes\n\n// Set Hardware mode to breath\nkeyboard.mode(\'breathe\');\n\n\n// Blinking\n// Set the keyboard.color() Before calling .blink()\n// Refer to examples/blinkMulti.js\n\n// Blink all the keyboard LEDs to 750ms\nkeyboard.blink(750);\n\n\n// Blink Only left and right regions at 750ms\nkeyboard.blink([\'left\',\'right\'], 750);\n\n\n// Use the default blink, time: 1000ms\nkeyboard.blink();\n\n\n// Stop the blink after 5000ms\nsetTimeout(keyboard.stopBlink, 5000);\n\n```\n\n\n\n## Colors\nColors are set\n\n\n\n\n## Examples\n\nYou can view more examples in the [example folder.](https://github.com/wearefractal/msi-keyboard/tree/master/examples)\n\n## LICENSE\n\n(MIT License)\n\nCopyright (c) 2013 Steve Lacy |  Fractal <contact@wearefractal.com>\n\nPermission is hereby granted, free of charge, to any person obtaining\na copy of this software and associated documentation files (the\n"Software"), to deal in the Software without restriction, including\nwithout limitation the rights to use, copy, modify, merge, publish,\ndistribute, sublicense, and/or sell copies of the Software, and to\npermit persons to whom the Software is furnished to do so, subject to\nthe following conditions:\n\nThe above copyright notice and this permission notice shall be\nincluded in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,\nEXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\nNONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE\nLIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION\nOF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION\nWITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n',
37 silly install resolved     readmeFilename: 'README.md',
37 silly install resolved     bugs: { url: 'https://github.com/wearefractal/msi-keyboard/issues' },
37 silly install resolved     _id: 'msi-keyboard@0.0.2',
37 silly install resolved     dist:
37 silly install resolved      { shasum: '07698074776f9188714fa5c62916dc9a968e578f',
37 silly install resolved        tarball: 'http://registry.npmjs.org/msi-keyboard/-/msi-keyboard-0.0.2.tgz' },
37 silly install resolved     _from: 'msi-keyboard@*',
37 silly install resolved     _npmVersion: '1.3.14',
37 silly install resolved     _npmUser: { name: 'fractal', email: 'contact@wearefractal.com' },
37 silly install resolved     maintainers: [ [Object] ],
37 silly install resolved     directories: {},
37 silly install resolved     _shasum: '07698074776f9188714fa5c62916dc9a968e578f',
37 silly install resolved     _resolved: 'https://registry.npmjs.org/msi-keyboard/-/msi-keyboard-0.0.2.tgz' } ]
38 info install msi-keyboard@0.0.2 into /home/schindler/Downloads/msi-klm
39 info installOne msi-keyboard@0.0.2
40 verbose installOne of msi-keyboard to /home/schindler/Downloads/msi-klm not in flight; installing
41 verbose lock using /home/schindler/.npm/_locks/msi-keyboard-325b25a69441a5ee.lock for /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard
42 silly install write writing msi-keyboard 0.0.2 to /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard
43 silly cache addNamed cb msi-keyboard@0.0.2
44 verbose unbuild node_modules/msi-keyboard
45 silly gentlyRm /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard is being purged from base /home/schindler/Downloads/msi-klm
46 verbose gentlyRm don't care about contents; nuking /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard
47 verbose tar unpack /home/schindler/.npm/msi-keyboard/0.0.2/package.tgz
48 verbose tar unpacking to /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard
49 silly gentlyRm /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard is being purged
50 verbose gentlyRm don't care about contents; nuking /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard
51 silly gunzTarPerm modes [ '755', '644' ]
52 silly gunzTarPerm extractEntry package.json
53 silly gunzTarPerm extractEntry .npmignore
54 silly gunzTarPerm extractEntry README.md
55 silly gunzTarPerm extractEntry LICENSE
56 silly gunzTarPerm extractEntry index.js
57 silly gunzTarPerm extractEntry .travis.yml
58 silly gunzTarPerm extractEntry examples/blink.js
59 silly gunzTarPerm extractEntry examples/blinkMulti.js
60 silly gunzTarPerm extractEntry examples/breathe.js
61 silly gunzTarPerm extractEntry examples/sample.js
62 silly gunzTarPerm extractEntry examples/wave.js
63 silly gunzTarPerm extractEntry lib/findKeyboard.js
64 silly gunzTarPerm extractEntry lib/setColor.js
65 silly gunzTarPerm extractEntry lib/setMode.js
66 silly gunzTarPerm extractEntry lib/constants.json
67 silly gunzTarPerm extractEntry test/findKeyboard.js
68 silly gunzTarPerm extractEntry test/main.js
69 silly gunzTarPerm extractEntry test/setColor.js
70 info preinstall msi-keyboard@0.0.2
71 silly prepareForInstallMany adding node-hid@* from msi-keyboard dependencies
72 silly cache add args [ 'node-hid@*', null ]
73 verbose cache add spec node-hid@*
74 silly cache add parsed spec { raw: 'node-hid@*',
74 silly cache add   scope: null,
74 silly cache add   name: 'node-hid',
74 silly cache add   rawSpec: '*',
74 silly cache add   spec: '*',
74 silly cache add   type: 'range' }
75 verbose addNamed node-hid@*
76 silly addNamed semver.valid null
77 silly addNamed semver.validRange *
78 silly addNameRange { name: 'node-hid', range: '*', hasData: false }
79 silly mapToRegistry name node-hid
80 silly mapToRegistry using default registry
81 silly mapToRegistry registry https://registry.npmjs.org/
82 silly mapToRegistry uri https://registry.npmjs.org/node-hid
83 verbose addNameRange registry:https://registry.npmjs.org/node-hid not in flight; fetching
84 verbose request uri https://registry.npmjs.org/node-hid
85 verbose request no auth needed
86 info attempt registry request try #1 at 15:18:39
87 verbose etag "4UVN0W5XEWPIWIHTLU6BBN1MC"
88 http request GET https://registry.npmjs.org/node-hid
89 http 304 https://registry.npmjs.org/node-hid
90 silly get cb [ 304,
90 silly get   { date: 'Sun, 05 Apr 2015 19:18:39 GMT',
90 silly get     server: 'Apache',
90 silly get     via: '1.1 varnish',
90 silly get     'last-modified': 'Sun, 05 Apr 2015 19:18:39 GMT',
90 silly get     'cache-control': 'max-age=60',
90 silly get     etag: '"4UVN0W5XEWPIWIHTLU6BBN1MC"',
90 silly get     age: '0',
90 silly get     'x-served-by': 'cache-jfk1023-JFK',
90 silly get     'x-cache': 'MISS',
90 silly get     'x-cache-hits': '0',
90 silly get     'x-timer': 'S1428261519.701099,VS0,VE76',
90 silly get     vary: 'Accept',
90 silly get     'content-length': '0',
90 silly get     'keep-alive': 'timeout=10, max=50',
90 silly get     connection: 'Keep-Alive' } ]
91 verbose etag https://registry.npmjs.org/node-hid from cache
92 verbose get saving node-hid to /home/schindler/.npm/registry.npmjs.org/node-hid/.cache.json
93 silly addNameRange number 2 { name: 'node-hid', range: '*', hasData: true }
94 silly addNameRange versions [ 'node-hid',
94 silly addNameRange   [ '0.0.13',
94 silly addNameRange     '0.0.14',
94 silly addNameRange     '0.0.15',
94 silly addNameRange     '0.1.0',
94 silly addNameRange     '0.1.1',
94 silly addNameRange     '0.2.0',
94 silly addNameRange     '0.2.1',
94 silly addNameRange     '0.2.2',
94 silly addNameRange     '0.2.3',
94 silly addNameRange     '0.3.1',
94 silly addNameRange     '0.3.2' ] ]
95 verbose addNamed node-hid@0.3.2
96 silly addNamed semver.valid 0.3.2
97 silly addNamed semver.validRange 0.3.2
98 silly cache afterAdd node-hid@0.3.2
99 verbose afterAdd /home/schindler/.npm/node-hid/0.3.2/package/package.json not in flight; writing
100 verbose afterAdd /home/schindler/.npm/node-hid/0.3.2/package/package.json written
101 silly install resolved [ { name: 'node-hid',
101 silly install resolved     description: 'USB HID device access library',
101 silly install resolved     version: '0.3.2',
101 silly install resolved     author:
101 silly install resolved      { name: 'Hans Hübner',
101 silly install resolved        email: 'hans.huebner@gmail.com',
101 silly install resolved        url: 'https://github.com/hanshuebner' },
101 silly install resolved     contributors: [ [Object] ],
101 silly install resolved     repository:
101 silly install resolved      { type: 'git',
101 silly install resolved        url: 'git://github.com/hanshuebner/node-hid.git' },
101 silly install resolved     scripts:
101 silly install resolved      { preupdate: 'sh get-hidapi.sh',
101 silly install resolved        preinstall: 'sh get-hidapi.sh',
101 silly install resolved        install: 'sh install.sh' },
101 silly install resolved     main: './index.js',
101 silly install resolved     engines: { node: '>=0.8.0' },
101 silly install resolved     license: 'MIT/X11',
101 silly install resolved     dependencies: {},
101 silly install resolved     devDependencies: {},
101 silly install resolved     gitHead: 'd9833cef3a4eff6110be3e1de5d8b5c8bb106500',
101 silly install resolved     bugs: { url: 'https://github.com/hanshuebner/node-hid/issues' },
101 silly install resolved     homepage: 'https://github.com/hanshuebner/node-hid',
101 silly install resolved     _id: 'node-hid@0.3.2',
101 silly install resolved     _shasum: '2414824b459313d1ca627fabdb4cb7a2506c0478',
101 silly install resolved     _from: 'node-hid@*',
101 silly install resolved     _npmVersion: '1.4.21',
101 silly install resolved     _npmUser: { name: 'hans', email: 'hans.huebner@gmail.com' },
101 silly install resolved     maintainers: [ [Object], [Object], [Object] ],
101 silly install resolved     dist:
101 silly install resolved      { shasum: '2414824b459313d1ca627fabdb4cb7a2506c0478',
101 silly install resolved        tarball: 'http://registry.npmjs.org/node-hid/-/node-hid-0.3.2.tgz' },
101 silly install resolved     directories: {},
101 silly install resolved     _resolved: 'https://registry.npmjs.org/node-hid/-/node-hid-0.3.2.tgz',
101 silly install resolved     readme: 'ERROR: No README data found!' } ]
102 info install node-hid@0.3.2 into /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard
103 info installOne node-hid@0.3.2
104 verbose installOne of node-hid to /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard not in flight; installing
105 verbose lock using /home/schindler/.npm/_locks/node-hid-ae83e13d8a2ab0cf.lock for /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid
106 silly install write writing node-hid 0.3.2 to /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid
107 silly cache addNamed cb node-hid@0.3.2
108 verbose unbuild node_modules/msi-keyboard/node_modules/node-hid
109 silly gentlyRm /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid is being purged from base /home/schindler/Downloads/msi-klm
110 verbose gentlyRm don't care about contents; nuking /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid
111 verbose tar unpack /home/schindler/.npm/node-hid/0.3.2/package.tgz
112 verbose tar unpacking to /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid
113 silly gentlyRm /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid is being purged
114 verbose gentlyRm don't care about contents; nuking /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid
115 silly gunzTarPerm modes [ '755', '644' ]
116 silly gunzTarPerm extractEntry package.json
117 silly gunzTarPerm extractEntry .npmignore
118 silly gunzTarPerm extractEntry README.md
119 silly gunzTarPerm extractEntry index.js
120 silly gunzTarPerm extractEntry binding.gyp
121 silly gunzTarPerm extractEntry get-hidapi.sh
122 silly gunzTarPerm extractEntry install.sh
123 silly gunzTarPerm extractEntry src/.npmignore
124 silly gunzTarPerm extractEntry src/buzzers.js
125 silly gunzTarPerm extractEntry src/powermate.js
126 silly gunzTarPerm extractEntry src/show-devices.js
127 silly gunzTarPerm extractEntry src/test-buzzers.js
128 silly gunzTarPerm extractEntry src/test-powermate.js
129 silly gunzTarPerm extractEntry src/test-ps3.js
130 silly gunzTarPerm extractEntry src/HID.cc
131 silly gunzTarPerm extractEntry src/wscript
132 info preinstall node-hid@0.3.2
133 verbose unsafe-perm in lifecycle true
134 silly install resolved []
135 verbose about to build /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid
136 info build /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid
137 verbose linkStuff [ false,
137 verbose linkStuff   false,
137 verbose linkStuff   false,
137 verbose linkStuff   '/home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules' ]
138 info linkStuff node-hid@0.3.2
139 verbose linkBins node-hid@0.3.2
140 verbose linkMans node-hid@0.3.2
141 verbose rebuildBundles node-hid@0.3.2
142 info install node-hid@0.3.2
143 verbose unsafe-perm in lifecycle true
144 info node-hid@0.3.2 Failed to exec install script
145 verbose unlock done using /home/schindler/.npm/_locks/node-hid-ae83e13d8a2ab0cf.lock for /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid
146 verbose about to build /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard
147 verbose unlock done using /home/schindler/.npm/_locks/msi-keyboard-325b25a69441a5ee.lock for /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard
148 verbose stack Error: node-hid@0.3.2 install: `sh install.sh`
148 verbose stack Exit status 1
148 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
148 verbose stack     at EventEmitter.emit (events.js:110:17)
148 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:14:12)
148 verbose stack     at ChildProcess.emit (events.js:110:17)
148 verbose stack     at maybeClose (child_process.js:1015:16)
148 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
149 verbose pkgid node-hid@0.3.2
150 verbose cwd /home/schindler/Downloads/msi-klm
151 error Linux 3.19.2-1-ARCH
152 error argv "/usr/bin/node" "/usr/bin/npm" "install" "msi-keyboard"
153 error node v0.12.2
154 error npm  v2.7.5
155 error code ELIFECYCLE
156 error node-hid@0.3.2 install: `sh install.sh`
156 error Exit status 1
157 error Failed at the node-hid@0.3.2 install script 'sh install.sh'.
157 error This is most likely a problem with the node-hid package,
157 error not with npm itself.
157 error Tell the author that this fails on your system:
157 error     sh install.sh
157 error You can get their info via:
157 error     npm owner ls node-hid
157 error There is likely additional logging output above.
158 verbose exit [ 1, true ]
159 verbose unbuild node_modules/msi-keyboard/node_modules/node-hid
160 info preuninstall node-hid@0.3.2
161 info uninstall node-hid@0.3.2
162 verbose unbuild rmStuff node-hid@0.3.2 from /home/schindler/Downloads/msi-klm/node_modules
163 verbose unbuild rmStuff in /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules
164 info postuninstall node-hid@0.3.2
165 silly gentlyRm /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid is being purged from base /home/schindler/Downloads/msi-klm
166 verbose gentlyRm don't care about contents; nuking /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid
167 silly vacuum-fs purging /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules/node-hid
168 silly vacuum-fs removing /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard/node_modules
169 silly vacuum-fs quitting because other entries in /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard
170 verbose unbuild node_modules/msi-keyboard
171 info preuninstall msi-keyboard@0.0.2
172 info uninstall msi-keyboard@0.0.2
173 verbose unbuild rmStuff msi-keyboard@0.0.2 from /home/schindler/Downloads/msi-klm/node_modules
174 info postuninstall msi-keyboard@0.0.2
175 silly gentlyRm /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard is being purged from base /home/schindler/Downloads/msi-klm
176 verbose gentlyRm don't care about contents; nuking /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard
177 silly vacuum-fs purging /home/schindler/Downloads/msi-klm/node_modules/msi-keyboard
178 silly vacuum-fs removing /home/schindler/Downloads/msi-klm/node_modules
179 silly vacuum-fs finished vacuuming up to /home/schindler/Downloads/msi-klm

$ node --version
v0.12.2

**Comment by stevelacy** [comment]
https://github.com/node-hid/node-hid/issues/90

**Comment by phaazon** [comment]
Ok so you close the issue “until node-hid fixes it”?

**Comment by stevelacy** [comment]
@phaazon what issue?

**Comment by phaazon** [comment]
This very one. I don’t get what the message is then. Your tool is broken because of a dependency. Does it mean you won’t provide any patch until the dependency updates and gets fixed?

**Comment by stevelacy** [comment]
This relies on a node module called `node-hid`, it can not be 'patched' to work on v0.12 as it relies on `node-hid` to control the HID devices.
#13 is currently tracking the progress of `node-hid` and v0.12
