### ISSUE TITLE
Linux Mint 17.3 (ubuntu 14.04) Trusty procedure

### ISSUE THREAD

**Issue by bash64** [wearefractal/msi-keyboard#33]
I have a chapter in my new book showing a working procedure for Linux Mint 17 users.
Hopefully links are not banned here:
http://bettyboopdatabase.atwebpages.com/book/

The book is free to download at the bottom of the page using the big green link.
A $5 payment is requested for the book.
I own an MSI gt70-2pe.

**Comment by stevelacy** [comment]
Reported spam - closing - locking.
