### ISSUE TITLE
Can lights become more than a gimmick? Alarm, visual cues, learning...

### ISSUE THREAD

**Issue by timofonic** [wearefractal/msi-keyboard#35]
# Stimulus as part of my concept of "ADHD Geek therapy" 
_(Sorry for the offtopic and some kind of "charity advertisement")_

- I'm a geek that has ADHD (Attention Defficit Hyperactivity-Disorder). Despite my inaccurate English and lack, lack of proper writing and able to do something with a proper order
 (see awful bad try to make a support group here [ADHD Geeks](https://github.com/adhdgeeks/ADHD-Geeks) and sorry for my inaccurate English and chaotic writing!) and would love to use all kind of ways to make me out of my massive distraction issues. 

I'm an electronics student, but I like computers too as equal. I'm a total fanatic of technology, I like both the hard and soft! 

If there's other ADHD Geeks that want to collaborate and are less chaotic and more mature than me, it would be very nice to make the idea get serious.

We get attracted by stimulus, so I consider we can use it in a positive way. My most productive moments are using fast rhythmic music that lack voices or has repetitive phrases that motivate me.

https://github.com/adhdgeeks/ADHD-Geeks/issues

## There's not cure 
It's something we must live with it
If we are properly trained and stimulated, we can use our "superpowers" for very creative and innovative stuff! 
There's lots of very brilliant people with ADHD and some people from the past are suspected to have had this condition.

## There's tons of ADHD denialists

- What's even worse: Lots of these have ADHD too!
* We need to get strong and make these people understand it, specially those people with ADHD but in denial phase.
 * I know you are afraid others may look you as inferior and don't want to "look a weirdo" despite over 50 years of research and very strong scientific facts about it. 

## How lights would help me as alarm?

- Giving me some kind of "epileptic" colours to alert and stimulate me to do things, combined with other stuff.
* We are dopamine addicts! We need to be stimulated and some of us even need prescription drugs to focus.

**Comment by stevelacy** [comment]
I have done it. Just write a nodejs app to run commands from a event bus.
Lol - I have OCD and ADD
